# Generated by Django 4.1.7 on 2023-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_favouritemovie_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritemovie',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
